### ISSUE TITLE
sizeHttp.getContentLength() = -1 除了加请求头还有先看重定向url

### ISSUE THREAD

**Issue by PopFisher** [yaowen369/DownloadHelper#18]
sizeHttp.getContentLength() = -1 
盲目的加上sizeHttp.setRequestProperty("Accept-Encoding", "identity");
也不对。如果被重定向了，要拿重定向之后的url重新请求才可以

哎，我看到你说你几百万的app里面验证了才敢用，没想到还是这么多bug，老板有点不负责任啊。老大已经让我重新写一个了，你这个坑太多了。
为了后面使用的人少踩坑，建议老板有空把这些bug修一下吧，重构一把，好歹对得起300多个赞，谢谢。

**Comment by yaowen369** [comment]
真的挺抱歉的。我这段就开始陆陆续续修复bug。

后来换了一家新公司，太忙了，所以已经一年多没管过这个项目了。

**Comment by yaowen369** [comment]
> sizeHttp.getContentLength() = -1
> 盲目的加上sizeHttp.setRequestProperty("Accept-Encoding", "identity");
> 也不对。如果被重定向了，要拿重定向之后的url重新请求才可以
> 
> 哎，我看到你说你几百万的app里面验证了才敢用，没想到还是这么多bug，老板有点不负责任啊。老大已经让我重新写一个了，你这个坑太多了。
> 为了后面使用的人少踩坑，建议老板有空把这些bug修一下吧，重构一把，好歹对得起300多个赞，谢谢。

后来想想这个项目，的确有很多不好的地方，虽然在上家公司项目中作为我们自己项目的下载模块，一切正常，但是那是我们自己设置的下载服务器。所以没那么多问题。 但是的确不够完善。

感谢大家指出问题。尽力做到对的起star该项目的同行。

**Comment by yaowen369** [comment]
1.4.0版本已经修正了重定向的问题。
感谢你提出的issue
