### ISSUE TITLE
回调问题

### ISSUE THREAD

**Issue by Johncuiqiang** [yaowen369/DownloadHelper#2]
博主,你在DownloadTask类中 这个位置如果这样写回调的是onstart方法,亲测发生异常走onStart
  } catch (Exception e){
            LogUtils.e(TAG, "下载过程发生失败");
            dbHolder.saveFile(mFileInfo);
            context.sendBroadcast(intent);
            e.printStackTrace();
 } finally {
需要更改一下,重新new 一个intent,然后mFileInfo.setDownloadStatus(DownloadStatus.FAIL);才会回调失败

**Comment by yaowen369** [comment]
好的，收到，我闲了仔细看一下。
非常感谢

**Comment by yaowen369** [comment]
> 博主,你在DownloadTask类中 这个位置如果这样写回调的是onstart方法,亲测发生异常走onStart
> } catch (Exception e){
> LogUtils.e(TAG, "下载过程发生失败");
> dbHolder.saveFile(mFileInfo);
> context.sendBroadcast(intent);
> e.printStackTrace();
> } finally {
> 需要更改一下,重新new 一个intent,然后mFileInfo.setDownloadStatus(DownloadStatus.FAIL);才会回调失败

该问题在1.4.0版本已经解决了
