### ISSUE TITLE
列表文件下载问题

### ISSUE THREAD

**Issue by nanchen2251** [yaowen369/DownloadHelper#6]
我看你这个是用的 广播机制更新；
我现在的需求是列表中支持多个文件下载，点击列表则下载，再次点击则暂停。

我用广播的话，我无法知道我当前是点击的哪个吧，是否可以通过回调处理？

**Comment by yaowen369** [comment]
广播也可以知道具体文件信息的。

可以参考demo类。

广播当中可以得到 File信息，File.java中包含了下载与文件的各种信息。

广播中是这样写的
```java
    FileInfo fileInfo = (FileInfo) intent.getSerializableExtra(DownloadConstant.EXTRA_INTENT_DOWNLOAD);
```
